name: Build Draco JS (asm.js, no wasm)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Draco
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake python3

      - name: Setup emsdk 3.1.45 and Build JS (asm.js)
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install 3.1.45
          ./emsdk activate 3.1.45
          source ./emsdk_env.sh
          cd ..
          mkdir build_js
          cd build_js
          env EMSCRIPTEN=$GITHUB_WORKSPACE/emsdk/upstream/emscripten emcmake cmake .. -DDRACO_JS_GLUE=ON -DDRACO_WASM=OFF -DCMAKE_BUILD_TYPE=Release
          emmake make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: draco-js-asm
          path: |
            build_js/draco_decoder.js
            build_js/draco_encoder.js
